@port = 3001
@host = localhost:{{port}}
@token = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhc3Npc3RhbnQtcHVibGljLWFwaSIsImV4cCI6IjIwMjQtMDEtMTJUMTY6MzU6NTAuMjE3OTU3KzA3OjAwIiwidXNlcl9pZCI6MX0.dmNJZkW0LqQKy5bj2q0AO-UDaBMarFCbfs7aoZmy1vE
@notification = notifications


###########
# AUTH #
###########
# Create
POST http://{{host}}/auth HTTP/1.1
Content-Type: application/json
{{token}}

{"username":"abc","password":"123456"}
###

# Read
GET http://{{host}}/api/v1/{{notification}}/2 HTTP/1.1
{{token}}
###

# Read
GET http://{{host}}/api/v1/{{notification}} HTTP/1.1
{{token}}
###
