@port = 3001
@host = coteccons.info
@token = Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhc3Npc3RhbnQtcHVibGljLWFwaSIsImV4cCI6IjIwMjQtMDEtMTJUMTY6MzU6NTAuMjE3OTU3KzA3OjAwIiwidXNlcl9pZCI6MX0.dmNJZkW0LqQKy5bj2q0AO-UDaBMarFCbfs7aoZmy1vE
@project = projects


###########
# AUTH #
###########
# Create
POST http://{{host}}/auth HTTP/1.1
Content-Type: application/json
{{token}}

{"username":"abc","password":"123456"}

############
# PROJECTS #
############
# CREATE

POST http://{{host}}/api/v1/{{project}} HTTP/1.1
Content-Type: application/json
{{token}}

{"name":"Pahama Paradise","code":"CTC003","manager_id":2,"region_id":1,"category_id":2,"address":"123 Binh Duong","start_date":"2006-01-02","end_date":"2012-05-02"}

############
# PROJECTS #
############
# UPDATE

PUT http://{{host}}/api/v1/{{project}}/13 HTTP/1.1
Content-Type: application/json
{{token}}

{"id":1,"name":"Panama Seaside","code":"CTC003","manager_id":1,"region_id":2,"category_id":3, "address":"123 Binh Duong - Updated","start_date":"2008-01-02","end_date":"2014-05-02"}

###########
# PROJECTS #
###########

# Read detail
GET https://{{host}}/api/v1/{{project}}/13 HTTP/1.1
{{token}}
###

# Read list
GET http://{{host}}/api/v1/{{project}} HTTP/1.1
{{token}}
###

# Delete
DELETE http://{{host}}/api/v1/{{project}}/11 HTTP/1.1
Content-Type: application/json
{{token}}
###

############
# CREATE MEMBER

POST http://{{host}}/api/v1/{{project}}/9/members HTTP/1.1
Content-Type: application/json
{{token}}

{"user_id":2}
###

# DELETE MEMBER
DELETE http://{{host}}/api/v1/{{project}}/8/members/4 HTTP/1.1
Content-Type: application/json
{{token}}
###

# LIST MEMBER

GET http://{{host}}/api/v1/{{project}}/9/members HTTP/1.1
Content-Type: application/json
{{token}}

###


############
# CREATE EXECUTOR

POST http://{{host}}/api/v1/{{project}}/9/executors HTTP/1.1
Content-Type: application/json
{{token}}

{"executor_id":2}
###

# DELETE MEMBER
DELETE http://{{host}}/api/v1/{{project}}/8/executors/1 HTTP/1.1
Content-Type: application/json
{{token}}
###

# LIST MEMBER

GET http://{{host}}/api/v1/{{project}}/9/executors HTTP/1.1
Content-Type: application/json
{{token}}

###

############
# CREATE PHASE

POST http://{{host}}/api/v1/projects/9/phases HTTP/1.1
Content-Type: application/json
{{token}}

{"name":"Móng","start_date":"2008-01-02","end_date":"2014-05-02"}
###

PUT http://{{host}}/api/v1/projects/9/phases/1 HTTP/1.1
Content-Type: application/json
{{token}}

{"name":"Móng - Updated","start_date":"2008-01-02","end_date":"2014-05-02"}
###

GET http://{{host}}/api/v1/projects/9/phases HTTP/1.1
Content-Type: application/json
{{token}}

###

GET http://{{host}}/api/v1/projects/9/phases/1 HTTP/1.1
Content-Type: application/json
{{token}}

###
